# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastai_coursep2',
                'doc_host': 'https://PythonBen.github.io',
                'git_url': 'https://github.com/PythonBen/fastai_coursep2',
                'lib_path': 'fastai_coursep2'},
  'syms': {'fastai_coursep2.core': {'fastai_coursep2.core.foo': ('core.html#foo', 'fastai_coursep2/core.py')}}}
